export const GET_USER = 'GET_USER';
export const GET_USER_START = 'GET_USER_START';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const GET_USER_LIST = 'GET_USER_LIST';
export const GET_USER_LIST_START = 'GET_USER_LIST_START';
export const GET_USER_LIST_ERROR = 'GET_USER_LIST_ERROR';

export const GET_NOT_DELETED_USER_LIST = 'GET_NOT_DELETED_USER_LIST';
export const GET_NOT_DELETED_USER_LIST_START = 'GET_NOT_DELETED_USER_LIST_START';
export const GET_NOT_DELETED_USER_LIST_ERROR = 'GET_NOT_DELETED_USER_LIST_ERROR';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_START = 'SET_CURRENT_USER_START';
export const SET_CURRENT_USER_ERROR = 'SET_CURRENT_USER_ERROR';

export const DEACTIVATE_USER = 'DEACTIVATE_USER';
export const DEACTIVATE_USER_START = 'DEACTIVATE_USER_START';
export const DEACTIVATE_USER_ERROR = 'DEACTIVATE_USER_ERROR';

export const ACTIVATE_USER = 'ACTIVATE_USER';
export const ACTIVATE_USER_START = 'ACTIVATE_USER_START';
export const ACTIVATE_USER_ERROR = 'ACTIVATE_USER_ERROR';

export const ADD_USER = 'ADD_USER';
export const ADD_USER_START = 'ADD_USER_START';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

export const CHANGE_LAYOUT = 'CHANGE_LAYOUT';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_ERRORS = 'GET_ERRORS';


export const CLEAR_ERROR_USER = 'CLEAR_ERROR_USER';

export const COLLAPSE_MENU = 'COLLAPSE_MENU';
export const COLLAPSE_TOGGLE = 'COLLAPSE_TOGGLE';
export const NAV_COLLAPSE_LEAVE = 'NAV_COLLAPSE_LEAVE';
export const NAV_CONTENT_LEAVE = 'NAV_CONTENT_LEAVE';
